name: ci

on: [pull_request, push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [14, 15]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{matrix.node}}
      - run: npm install
      - run: npm run  build
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm test
